blank_issues_enabled: false
contact_links:
  - name: Suggest a feature
    url: https://github.com/Radiokot/photoprism-android-client/discussions/categories/ideas
    about: Suggest a feature for the gallery or vote on existing suggestion
